version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - filestorage:/tmp
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - wms_network

  minio:
    image: minio/minio
    hostname: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpass
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - wms_network

volumes:
  mysql_data: {}
  minio_data: {}
  openldap_data:
    driver: local
  filestorage:

networks:
  wms_network:
    driver: bridge
